name: abaplint

on: [push]

jobs:
  abaplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: abaplint
      uses: abaplint/actions-abaplint@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
